# Generated by Django 4.1.7 on 2023-03-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_completed_tasks', models.BooleanField(default=False)),
                ('task_sort_order', models.CharField(choices=[('date_created', 'Date Created'), ('due_date', 'Due Date'), ('priority', 'Priority')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
